FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends libgomp1 && rm -rf /var/lib/apt/lists/*

COPY requirements.txt pyproject.toml ./
COPY src ./src
RUN pip install --no-cache-dir -r requirements.txt && pip install --no-cache-dir -e .

COPY artifacts ./artifacts

EXPOSE 8000
CMD ["uvicorn", "edf.serving.api:app", "--host", "0.0.0.0", "--port", "8000"]
